name: MNS Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: alibabacloud-gateway-mns/java
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn test -B -Dgpg.skip=true
