name: SLS Python2 Test

on:
  push:
    branches: [ master ]
    paths:
      - 'alibabacloud-gateway-sls/**'
      - '.github/workflows/sls_python2.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'alibabacloud-gateway-sls/**'
      - '.github/workflows/sls_python2.yml'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: alibabacloud-gateway-sls/python2
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: python:2.7-buster

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install setuptools typing coverage
        pip install ../util/python2
        python setup.py install
    - name: Test with unittest
      run: python -m unittest discover -s tests
